var express=require('express');
var router=express.Router();
var cat=require('../models/categoryModel');
//localhost:3000/category
router.get('/',function(req,res,next){

    cat.getAllCategories(function(err,rows){

        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/category/1
router.get('/:id',function(req,res,next){
    cat.getCategoryById(req.params.id,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);  
         }
    });
});
//localhost:3000/category
router.post('/',function(req,res,next){
    cat.addCategory(req.body,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/category/1
router.delete('/:id',function(req,res,next){
    cat.deleteCategory(req.params.id,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/category
router.put('/',function(req,res,next){
    cat.editCategory(req.body,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
module.exports=router;
