var express=require('express');
var router=express.Router();
var cust=require('../models/customerModel');
//localhost:3000/customer
router.get('/',function(req,res,next){

    cust.getAllCustomers(function(err,rows){

        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/customer/1
router.get('/:id',function(req,res,next){
    cust.getCustomerById(req.params.id,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);  
         }
    });
});
//localhost:3000/customer
router.post('/',function(req,res,next){
    cust.addCustomer(req.body,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/customer/1
router.delete('/:id',function(req,res,next){
    cust.deleteCustomer(req.params.id,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
//localhost:3000/customer
router.put('/',function(req,res,next){
    cust.editCustomer(req.body,function(err,rows){
        if(err){
            res.json(err);
        }
        else{
            res.json(rows);
        }
    });
});
module.exports=router;
